; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
extra_scripts = pre:extra/pre_build.py
lib_deps = 
	https://github.com/felis/USB_Host_Shield_2.0#1.7.0
;upload_protocol = usbasp
;upload_flags = 
;    -Pusb
;    -v
;    -e
;    -b900